name: ci-guide
on: 
  pull_request:
    branches-ignore:
      - staging
  workflow_dispatch:
jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: init
        run: |
          url="https://github.com/rust-lang/mdBook/releases/download/v0.4.47/mdbook-v0.4.47-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: build
        run: |
          cd guide
          cmake -P build.cmake || exit 1
          ls book
